<?php require VIEWS_PATH . 'includes/header.phtml';?>
<div class="container">
   <!-- Main component for a primary marketing message or call to action -->
   <div class="jumbotron">
        <h1>Sobre</h1>        
    </div>
           <div class="col-md-12">
           <h2>A Instituição</h2>
             <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam nemo soluta porro magni
              illum ratione. Voluptas odio cumque rem velit doloribus, nihil eum veritatis ea eos aliquid 
              voluptatum quos quibusdam.
              </p>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam nemo soluta porro magni
              illum ratione. Voluptas odio cumque rem velit doloribus, nihil eum veritatis ea eos aliquid 
              voluptatum quos quibusdam.
              </p>
              <h2>Valores</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam nemo soluta porro magni
              illum ratione. Voluptas odio cumque rem velit doloribus, nihil eum veritatis ea eos aliquid 
              voluptatum quos quibusdam.
              </p>
           </div>
      

</div>
<?php require VIEWS_PATH . 'includes/footer.phtml';?>