<?php require VIEWS_PATH . 'includes/header.phtml';?>
<div class="container">
   <!-- Main component for a primary marketing message or call to action -->
   <div class="jumbotron">
      <h1>Entre em contato conosco</h1>        
    </div>
     
        <div class="col-md-12">
           <h2>Fale conosco por meio dos contatos abaixo!</h2>
           <p>
              Telefone: <a href="tel:98999999999"><strong>98 9 9999-9999</strong></a><br>
              Email: <a href="mailto:email@email.com"><strong>email@email.com</strong></a>
           </p>
        </div>    
      <form>
      <div class="form-group">
        <label for="nome">Nome (*Campo obrigatório)</label>
        <input type="text" class="form-control" id="nome" placeholder="Nome Completo" name="name">
      </div>
      <div class="form-group">
        <label for="email">Email (*Campo obrigatório)</label>
        <input type="email" class="form-control" id="email" placeholder="Seu melhor Email" name="email">
      </div>
      <div class="form-group">
        <label for="assunto">Assunto</label>
        <input type="text" class="form-control" id="assunto" placeholder="Assunto" name="subject">
      </div>   
      <div class="form-group">
         <label for="message">Mensagem</label>
         <textarea name="message" id="message" cols="30" rows="10" class="form-control"></textarea>
      </div>   
      <button type="submit" class="btn btn-default">Submit</button>
    </form>

</div>
<?php require VIEWS_PATH . 'includes/footer.phtml';?>