<?php require VIEWS_PATH . 'includes/header.phtml';?>
<div class="container">
   <!-- Main component for a primary marketing message or call to action -->
   <div class="jumbotron">
        <h1>Bem vindo ao Projeto 1</h1>
        <p>
          Projeto criado  no curso PHP Orientado a Objetos da Code Experts learning.
        </p>
          <a class="btn btn-lg btn-primary" href="http://bit.ly/ce-learn" role="button">Saiba mais &raquo;</a>
        </p>
      </div>

</div>
<?php require VIEWS_PATH . 'includes/footer.phtml';?>